config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'

  resources :pigs, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pig
end

app/models/pig.rb
class Pig < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings
  has_one_attached :photo

  validates :name, presence: true
  validates :age, presence: true
  validates :profession, presence: true
  validates :bio, presence: true, length: { minimum: 100 }
  validates :weight, presence: true
  validates :price, presence: true
  validates :address, presence:true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pigs, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :avatar

  # validates :first_name, presence: true
  # validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @user = current_user
    @pig = Pig.find(params[:pig_id])
    @booking.pig = @pig
    @booking.user = @user
    @booking.save
    redirect_to pig_path(@pig), notice: "Your booking was succesfull!"
  end

  private
  def booking_params
    params.require(:booking).permit(:booking_date)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def dashboard

    @offered_pigs = Pig.where(user: current_user)
    @bookings = current_user.bookings
  end
end

app/controllers/pigs_controller.rb
class PigsController < ApplicationController
  def index
    @pigs = Pig.all
    @markers = @pigs.geocoded.map do |pig|
      {
        lat: pig.latitude,
        lng: pig.longitude,
        info_window: render_to_string(partial: "info_window", locals: { pig: pig }),
        image_url: helpers.asset_url('pigmarker.png')
      }
    end
  end

  def show
    @booking = Booking.new
    @pig = Pig.find(params[:id])
  end

  def new
    @pig = Pig.new
  end

  def create
    @pig = Pig.new(pig_params)
    @pig.user = current_user
    if @pig.save
      redirect_to pigs_path
    else
      render :new
    end
  end

  def dashboard
    @user = current_user
    @offered_pigs = Pig.where(user: @user)
    @pigs = Pig.all
    #@bookings = Pig.where(bookings belong to current user )


  end

  private

  def pig_params
    params.require(:pig).permit(:name, :weight, :age, :profession, :bio, :photo, :price, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container d-flex">

<!-- Profile card-->
  <div id = "card-profile" class="card text-center" style="width: 40%;">
    <img id= "profile-pic" src="https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80 " class="card-img-top rounded-circle" alt="...">
  <div class="card-body">
      <h2 class="card-title">
        <strong>
          <%= current_user.first_name %> <%= current_user.last_name%>
        </strong>
      </h2>
      <div id ="profile-items" class="footer-links">
        <a href="#"><i class="far fa-envelope"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
      </div>

      <div class= "dashboard-info">
        <h4><strong>You own:</strong></h4>
        <h4><%= current_user.pigs.count %> 🐽</h4>
        <a class="btn btn-primary btn-width" href="/pigs/new">Add a Pig</a>
        </div>

      <div class="spacer dashboard-info">
        <h4><strong>Current Bookings:</strong></h4>
        <h4><%= current_user.bookings.count %> 🐽</h4>
        <a class="btn btn-primary btn-width" href="/pigs">Book a Pig</a>

      </div>


<!--       </div> -->

    </div>
  </div>

<!-- Offer card-->
    <div >
<!-- Pig cards -->
    <div class = "pig-overview">
    <div class="dashboard-header">
    <h2 class="dashboard-title"><strong>My Pigs</strong></h2>
    </div>
     <div class="row justify-content-start no-margin">

          <% @offered_pigs.each do |p| %>
          <div class="col-6" align="center">
            <div class="card pig-dashboard-card" style="width: 22rem;">
              <%= image_tag p.photo, class:"card-img-top" %>
                <div class="card-body card-body-dashboard">
                  <div>
                    <h2><%=p.name%></h2>
                  </div>
                  <h2><%=p.price%> € per day</h2>
                  </div>
            </div>
          </div>
          <% end %>
      </div>
</div>

<div class = "pig-overview">
  <div class="dashboard-header">
      <h2 class="dashboard-title"><strong>My Pig Bookings</strong></h2>
      </div>
          <div class="row justify-content-start no-margin">

            <%if current_user.bookings.present? %>
            <% @bookings.each do |booking| %>

          <div class="col-6">
            <div class="card pig-dashboard-card" style="width: 22rem;">
              <%= image_tag booking.pig.photo, class:"card-img-top" %>
                <div class="card-body card-body-dashboard">
                  <div>
                    <h2><%=booking.pig.name%></h2>
                  </div>
                  <h2><%=booking.pig.price%> € per day</h2>
                  </div>

           <!--      <h5 class="card-title"><%=booking.pig.name%></h5>
                <p class="card-text">...</p>
                <a href="#" class="btn btn-primary">Go somewhere</a> -->
              </div>
            </div>
          <% end %>
          <% end %>

          </div>
      </div>

    </div>





  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url( <%= image_path "banner.jpg" %>)">
  <div class="container">
    <h1>Pick a Pig</h1>
    <p>Because without a pig... <br> Is life actually worth living?</p>
     <%= link_to "Book your pig", pigs_path, id: "landing-page-button", class: "btn btn-primary" %>

  </div>
</div>



<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div class="side-image-box" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url( <%= image_path "home-side-image.jpg" %>)">
      <h3 id="side-image-box-header">Book your pig for any occasion</h3>
      <p id="side-image-box-text-top">Do you need a to do your taxes? <br> The doctor does not have time for you? <br> Your business needs a UI-Designer?</p>
      <p id="side-image-box-text-bottom">Your pig has more skills than your boss? <br> No matter if you seek a pig or want to offer your pig´s services <br> Pick a Pig can help! </p>
      <div class= side-image-box-button>
        <%= link_to "Discover lovely pigs in your area", pigs_path, class: "btn btn-primary" %>
      </div>
    </div>
      <div class="right-column-pigs">
        <div class="column-pig">
          <h5 class= "column-pig-header text-center">Our newest professional pig</h5>
          <div class="card-product">
            <img <%= image_tag Pig.last.photo %> 
            <div class="card-product-infos">
              <h2 class="column-pig-link"><%= link_to Pig.last.name, pigs_path %></h2>
              <p>The <%= Pig.last.weight %> kg <%= Pig.last.profession %>!</p>
              <p> Living in <%= Pig.last.address %>. <br> <%= Pig.last.name %> is wating for you! </p>
              <p class="font-weight-bold"><%= Pig.last.price %> € per day</p> 
            </div>
          </div>
          <div class="column-pig">
          <h5 class="column-pig-header text-center">Our pig of the year</h5>
          <div class="card-product">
            <img <%= image_tag Pig.first.photo %> 
            <div class="card-product-infos">
              <h2 class="column-pig-link"><%= link_to Pig.first.name, pigs_path %></h2>
              <p>The <%= Pig.first.weight %> kg <%= Pig.first.profession %>!</p>
              <p> Living in <%= Pig.first.address %>. <br><%= Pig.first.name %> is holding this title with pride.</p>
              <p class="font-weight-bold"><%= Pig.first.price %> € per day</p> 
            </div>
          </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/pigs/_form.html.erb
<%= simple_form_for(@pig) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.input :age %>
    <%= f.input :address %>
    <%= f.input :weight %>
    <%= f.input :profession %>
    <%= f.input :bio %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pigs/_info_window.html.erb
<div class="pig-window">
  <%= image_tag pig.photo, class:"pig-image" %>
  <ul class= "pig-property-list">
    <li class= "pig-name"><%= link_to pig.name, pig_path(pig) %></li>
    <li class="pig-address"><%= pig.address %></li>
    <li class="pig-price font-weight-bold"><%= pig.price %>€ per day</li>
  </ul>
</div>

app/views/pigs/index.html.erb
<div class="container">
  <h1 class = "index-header">Pick A Pig For Your Purpose</h1>
  <div class="index-all">

    <div class= "pig-grid">
      <% @pigs.each do |p| %>
      <div class= "grid-pig">
        <div>
          <%= image_tag p.photo, class:"pig-image" %>
          <ul class= "pig-property-list">
            <li class= "pig-name"><%= link_to p.name, pig_path(p) %></li>
            <li class="pig-list-item"><%= p.profession %></li>
            <li class="pig-list-item"><%= p.age %> years old</li>
            <li class="pig-list-item"><%= p.weight %> kg</li>
            <li class="pig-list-item pig-adress"><%= p.address %></li>
            <li class="pig-list-item  font-weight-bold"><%= p.price %> € per day</li>
          </ul>
        </div>
        <p class="pig-bio"> <%= p.bio %></p>
      </div>
      <% end %>
    </div>
    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/pigs/new.html.erb
<div class= container><h1>Add a new pig!</h1>
<%= render 'form', pig: @pig %>
<%= link_to 'Back', pigs_path %>
</div>

app/views/pigs/show.html.erb
<!-- <div class="container">
    <div class="card-show">
      <%=image_tag @pig.photo%>
    <div class="card-show-infos">
      <div class="card-show-title">
        <h2><%= @pig.name %></h2>
      </div>
       <ul class="pig-list">
          <li>Weight:</u> <%= @pig.weight %></li>
          <li><u>Age:</u> <%= @pig.age %></li>
          <li><u>Profession:</u> <%= @pig.profession %></li>
          <li><u>Bio:</u> <%= @pig.bio %></li>
          <li><u>Price:</u> <%= @pig.price %> € per day</li>
        </ul>
        <div> -->
          <!-- Button trigger modal -->





<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= cl_image_path @pig.photo.key%>')">
  <div class="container">
    <h1>Pick a Pig</h1>
    <p>Because without a pig... <br> Is life actually worth living?</p>
  </div>
</div> -->
<div class= "container">
<div class="row">
  <div class="col-4">
  <div class ="pig-info">
    <h1><strong><%= @pig.name %></strong></h1>
      <div id ="pig-stars" class="footer-links">
        <i class="fas fa-star"></i></a>
        <i class="fas fa-star"></i></a>
        <i class="fas fa-star"></i></a>
        <i class="fas fa-star"></i></a>
        <i class="fas fa-star"></i></a>
      </div>
        <h6 class="spacer2"><strong>Weight:</strong> <%= @pig.weight %>kg</h6>
        <h6 class="spacer2"><strong>Age:</strong>  <%= @pig.age %></h6>
        <h6 class="spacer2"><strong>Profession:</strong>  <%= @pig.profession %></h6>
        <div class="text-justify">
        <h6 class="spacer2"><strong>Bio:</strong>  <%= @pig.bio %></h6>
        <h6 class="spacer2"><strong>Price:</strong>  <%= @pig.price %> € per day</h6>
      </div>
      <div>
    <button id="show-button" type="button" class="btn btn-primary spacer" data-toggle="modal" data-target="#exampleModal">
            Book now
    </button>
      </div>
    <% unless @pig.bookings.where(user: current_user).empty?%>
    <p style="color:green"><%= "booked"%></p>
    <% end %>
  </div>
  </div>
  <div class="col-8">
    <div class="background-image-pig" style= "background-image:url('<%=cl_image_path @pig.photo.key, id:"pig-picture"%>')" ></div> 
  </div>
</div>
</div>





          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Choose a date</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <%= simple_form_for [@pig, @booking] do |f| -%>
                  <%= f.input :booking_date, as: :date %>
                  <%= f.submit %>

                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> for Pigs!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://i.pinimg.com/564x/a3/98/9e/a3989e7f3734833c51cee16723f90910.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Pigs 🐽", pigs_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>